[gatekeep] improved chkpower function. Code reviewed by Belay

diff --git a/t3/gatekeep b/t3/gatekeep
--- a/t3/gatekeep
+++ b/t3/gatekeep
@@ -433,7 +433,7 @@ chkpower () {
 
 	echo "check if config file exists"
 		echo -ne "locating power_mgmt.conf..."
-		if [ -f config ]; then
+		if [ -f $config ]; then
 			echo -n "power management config file exists"
 			echo_success
 		else
@@ -444,13 +444,14 @@ chkpower () {
 
 	echo "check if executable file exists"
 		echo -ne "locating executable file..."
-		if [ -f exc ]; then
+		if [ -f $exc ]; then
 			echo -n "power management config file exists"
 			echo_success
 			echo -ne "check if file is executable..."
-			if [ -x exc ]; then
+			if [ -x $exc ]; then
 				echo -n "file is executable"
 				echo_success
+				echo
 			else
 				echo -n "file not set to executable!"
 				echo_failure
@@ -463,20 +464,36 @@ chkpower () {
 
 	echo "check if script directory exists"
 		echo -ne "locating directory..."
-		if [ -d dir ]; then
+		if [ -d $dir ]; then
 			echo -n "power management scripts directory exists"
 			echo_success
+			echo
 		else
 			echo -n "directory not found!"
 			echo_failure
 			return 1
 
 	echo "check chkconfig if power management is included"
-
+		#skipped for now
 
 	echo "check if power management was autostarted"
+		local status=`service powerinit status 
+		if [[ $? -=eq 0 ]]; then
+			echo -ne "started"
+			echo_success
+			echo
+		else
+			echo -ne "not started or failed!"
+			echo_failure
+			return 1
+		fi
 
 	return 0
+}
+
+# Function for checking BT Sync Components
+chkbt () {
+	
 }
 
 # Function to check the exit status number, and exit if it is not 0
